apiVersion: v1
kind: ConfigMap
metadata:
  name: oidc-discovery-provider
  namespace: spire
data:
  oidc-discovery-provider.conf: |
    log_level = "INFO"
    # TODO: Replace MY_DISCOVERY_DOMAIN with the FQDN of the Discovery Provider that you will configure in DNS
    domain = "demo-oidc.identitydigest.com"
    acme {
        directory_url = "https://acme-v02.api.letsencrypt.org/directory"
        cache_dir = "/run/spire"
        tos_accepted = true
        # TODO: Change MY_EMAIL_ADDRESS with your email
        email = "someone@gmail.com"
    }
    set_key_use = true
    workload_api {
      socket_path = "/run/spire/sockets/agent.sock"
      trust_domain = "example.org"
    }
    #registration_api {
    #   socket_path = "/run/spire/sockets/registration.sock"
    #}